[package]
name = "bin"
version.workspace = true
edition.workspace = true

[features]
reload = ["ui/reload"]

[dependencies]
ui.workspace = true
hot_ice.workspace = true
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = [
    "env-filter",
    "registry",
] }
tracing-error = "0.2.1"
