
[workspace]
package.edition = "2024"
package.version = "0.1.0"
members = ["src/hot_state", "src/ui"]

[workspace.dependencies]
hot_ice = { path = "../.." }
ui = { path = "src/ui" }
serde = { version = "1.0", features = ["derive"] }
